%%%  FIR  %%%
clc;
clear all;
close all;

Fs = 1000;                 
t = 0:1/Fs:1;              
x = sin(2*pi*50*t) + sin(2*pi*200*t) + sin(2*pi*400*t);
N = 50;                    
Wc_low  = 0.3;
Wc_high = 0.3;
Wc_band = [0.3 0.6];
Wc_stop = [0.3 0.6];
window = hamming(N+1);
h_low  = fir1(N, Wc_low,  'low',      window);
h_high = fir1(N, Wc_high, 'high',     window);
h_band = fir1(N, Wc_band, 'bandpass', window);
h_stop = fir1(N, Wc_stop, 'stop',     window);
y_low  = filter(h_low,  1, x);
y_high = filter(h_high, 1, x);
y_band = filter(h_band, 1, x);
y_stop = filter(h_stop, 1, x);
[H_low,  f] = freqz(h_low,  1, 1024, Fs);
[H_high, f] = freqz(h_high, 1, 1024, Fs);
[H_band, f] = freqz(h_band, 1, 1024, Fs);
[H_stop, f] = freqz(h_stop, 1, 1024, Fs);
figure;
subplot(5,1,1);
plot(t, x); grid on;
title('Input Signal'); ylabel('Amplitude');
subplot(5,1,2);
plot(t, y_low); grid on;
title('Low Pass Output (Hamming Window)'); ylabel('Amplitude');
subplot(5,1,3);
plot(t, y_high); grid on;
title('High Pass Output (Hamming Window)'); ylabel('Amplitude');
subplot(5,1,4);
plot(t, y_band); grid on;
title('Band Pass Output (Hamming Window)'); ylabel('Amplitude');
subplot(5,1,5);
plot(t, y_stop); grid on;
title('Band Stop Output (Hamming Window)'); xlabel('Time (s)'); ylabel('Amplitude');
figure;
subplot(2,2,1);
plot(f, abs(H_low)); grid on;
title('Low Pass FIR (Hamming)');
xlabel('Frequency (Hz)'); ylabel('|H(f)|');
subplot(2,2,2);
plot(f, abs(H_high)); grid on;
title('High Pass FIR (Hamming)');
xlabel('Frequency (Hz)'); ylabel('|H(f)|');
subplot(2,2,3);
plot(f, abs(H_band)); grid on;
title('Band Pass FIR (Hamming)');
xlabel('Frequency (Hz)'); ylabel('|H(f)|');
subplot(2,2,4);
plot(f, abs(H_stop)); grid on;
title('Band Stop FIR (Hamming)');
xlabel('Frequency (Hz)'); ylabel('|H(f)|');